
services:
  halobe:
    container_name: halobe
    build:
      context: ./haloBE  # Correct build context for backend
      dockerfile: Dockerfile
    image: halobe:latest
    ports:
      - "4000:4000"  # Backend port
    restart: always
    networks:
      - halo-network
    environment:
      - MONGO_URI=mongodb://mongodb:27017/capro

  halofe:
    container_name: halofe
    build:
      context: ./haloFE  # Correct build context for frontend
      dockerfile: Dockerfile
    image: halofe:latest
    ports:
      - "3000:3000"  # Frontend port
    restart: always
    networks:
      - halo-network

  mongodb:
    image: mongo:4.2.1-bionic
    ports:
      - "27017:27017"
    volumes:
      - dbdata:/data/db
    networks:
      - halo-network

volumes:
  dbdata:

networks:
  halo-network:
    driver: bridge
